import "./globals.css";

// Components
import Navbar from "@/components/Navbar";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`font-poppins`}>
                <Navbar />
                <div>{children}</div>
            </body>
        </html>
    );
}
